# Generated by Django 6.0.7 on 2026-08-16 10:26

import django.db.models.deletion
import game.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("settings_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTING", "Starting"),
                            ("ROUND_ACTIVE", "Round Active"),
                            ("ROUND_LOCKED", "Round Locked"),
                            ("ROUND_RESULT", "Round Result"),
                            ("GAME_OVER", "Game Over"),
                        ],
                        default="STARTING",
                        max_length=20,
                    ),
                ),
                ("current_round_index", models.IntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("avatar", models.CharField(default="bot", max_length=30)),
                ("device_token", models.CharField(db_index=True, max_length=128)),
                ("games_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("best_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("final_score", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=1)),
                ("best_streak", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="game.game",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results",
                        to="game.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "-final_score"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=game.models.generate_room_code,
                        max_length=5,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("IN_GAME", "In Game"),
                            ("CLOSED", "Closed"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_rooms",
                        to="game.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rounds_count",
                    models.IntegerField(choices=[(3, 3), (5, 5), (7, 7)], default=3),
                ),
                (
                    "round_duration_seconds",
                    models.IntegerField(
                        choices=[(15, 15), (30, 30), (45, 45)], default=30
                    ),
                ),
                (
                    "enabled_challenge_types",
                    models.JSONField(default=game.models.default_challenge_types),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="game.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="game.room",
            ),
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("COLOR", "Color"),
                            ("SHAPE", "Shape"),
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("PATTERN", "Pattern"),
                            ("TRANSPARENCY", "Transparency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("LOCKED", "Locked"),
                            ("RESULT", "Result"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="RoomPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_memberships",
                        to="game.profile",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_players",
                        to="game.room",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "profile"), name="unique_room_profile"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerRoundState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SEARCHING", "Searching"), ("DONE", "Done")],
                        default="SEARCHING",
                        max_length=20,
                    ),
                ),
                ("attempts_used", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_states",
                        to="game.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_states",
                        to="game.round",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("round", "profile"), name="unique_round_profile_state"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="submissions/"),
                ),
                ("image_base64", models.TextField(blank=True, default="")),
                ("valid", models.BooleanField(blank=True, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("is_override", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField(default=0)),
                ("streak_bonus", models.IntegerField(default=0)),
                ("commentary", models.TextField(blank=True, default="")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="game.profile",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="game.round",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("round", "profile", "attempt_number"),
                        name="unique_round_profile_attempt",
                    )
                ],
            },
        ),
    ]
